### ISSUE TITLE
Unable to install package async_upnp_client>=0.33

### ISSUE THREAD

**Issue by gzapata90** [rytilahti/homeassistant-upnp-availability#22]
I was unable to install the integration and got the errors below:

```
Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 8:52:08 PM (3 occurrences)
Last logged: 8:52:18 PM

Unable to install package async_upnp_client>=0.33: ERROR: Cannot install async_upnp_client>=0.33 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip
```

```
Logger: aiohttp.server
Source: requirements.py:267
First occurred: 8:52:55 PM (2 occurrences)
Last logged: 9:19:06 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 226, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 244, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 829, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 379, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 51, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 170, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 185, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 245, in async_process_requirements
    self._raise_for_failed_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 267, in _raise_for_failed_requirements
    raise RequirementsNotFound(integration, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for upnp_availability not found: ['async_upnp_client>=0.33'].
```

I got as far as adding the custom HACS repository, restarting HA, but when I tried to install the integration ("+ Add Integration" in Settings > Devices and Services) I got an HTTP 500 error on the UI, which prompted me to search the logs and found what I pasted above.

Digging around the source code, looks like the problem could be due to a version mismatch between [requirements.txt](https://github.com/rytilahti/homeassistant-upnp-availability/blob/master/requirements.txt#L1) and [manifest.json](https://github.com/rytilahti/homeassistant-upnp-availability/blob/master/custom_components/upnp_availability/manifest.json#L8)? I don't know how these HA integrations work (I'm very new to home assistant), so I'm putting the observation here for visibility instead of creating a PR. On my local machine I tried modifying the version in the manifest file to match the requirements file (`async_upnp_client>=0.32`) and the installation succeeded.

**Comment by rytilahti** [comment]
Which version of homeassistant are you running? The recent versions should use 0.33 (see https://github.com/home-assistant/core/blob/2023.1.4/requirements_all.txt#L371) so there should be no version conflict. Unfortunately, the error message does not show the packages that are causing this conflict...

The information relevant for homeassistant is contained in `manifest.json`, the requirements.txt is ignored by it. I'm not sure if downgrading to async-upnp-client 0.32 works with the current git master (I doubt, as #21 was a breaking change in the library).

As how to solve this, if you are running an older than 2023.1 please try to update it. If that's not doable, I could try to introduce a change to fix the backwards compatibility with older async-upnp-client versions, but I'd rather avoid doing that if possible...

**Comment by gzapata90** [comment]
The problem was the Home Assistant version I was running, as you pointed out. I updated to the most recent and installation went smoothly. Thanks for the help!
